sonar.host.url=http://localhost:9000
sonar.token=REEMPLAZAR_CON_TU_TOKEN_DE_SONARQUBE

sonar.projectKey=sigi-web
sonar.projectName=SIGI OTI - Sistema Integrado de Gestion de Incidencias - Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**, **/*.spec.ts, src/app/environments/**, src/app/api/fn/**, src/app/api/api.ts, src/app/api/api-configuration.ts, src/app/api/request-builder.ts, src/app/api/strict-http-response.ts
sonar.coverage.exclusions=**/node_modules/**, src/main.ts, src/app/environments/**, src/app/api/fn/**, src/app/api/api.ts, src/app/api/api-configuration.ts, src/app/api/request-builder.ts, src/app/api/strict-http-response.ts

sonar.typescript.lcov.reportPaths=coverage/sigi-web/lcov.info
sonar.javascript.lcov.reportPaths=coverage/sigi-web/lcov.info
sonar.sourceEncoding=UTF-8
