/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Apiauthlogin$Params } from './fn/operations/apiauthlogin';
export { apiauthlogin } from './fn/operations/apiauthlogin';
export type { Apiauthrefresh$Params } from './fn/operations/apiauthrefresh';
export { apiauthrefresh } from './fn/operations/apiauthrefresh';
export type { Apiauthlogout$Params } from './fn/operations/apiauthlogout';
export { apiauthlogout } from './fn/operations/apiauthlogout';

export type { Apiincidentinsert$Params } from './fn/operations/apiincidentinsert';
export { apiincidentinsert } from './fn/operations/apiincidentinsert';
export type { Apiincidentgetall$Params } from './fn/operations/apiincidentgetall';
export { apiincidentgetall } from './fn/operations/apiincidentgetall';
export type { Apiincidentgetbycode$Params } from './fn/operations/apiincidentgetbycode';
export { apiincidentgetbycode } from './fn/operations/apiincidentgetbycode';
export type { Apiincidentassign$Params } from './fn/operations/apiincidentassign';
export { apiincidentassign } from './fn/operations/apiincidentassign';
export type { Apiincidentupdate$Params } from './fn/operations/apiincidentupdate';
export { apiincidentupdate } from './fn/operations/apiincidentupdate';
export type { Apiincidentstart$Params } from './fn/operations/apiincidentstart';
export { apiincidentstart } from './fn/operations/apiincidentstart';
export type { Apiincidentresolve$Params } from './fn/operations/apiincidentresolve';
export { apiincidentresolve } from './fn/operations/apiincidentresolve';
export type { Apiincidentclose$Params } from './fn/operations/apiincidentclose';
export { apiincidentclose } from './fn/operations/apiincidentclose';
export type { Apiincidentreopen$Params } from './fn/operations/apiincidentreopen';
export { apiincidentreopen } from './fn/operations/apiincidentreopen';

export type { Apiincidentcommentinsert$Params } from './fn/operations/apiincidentcommentinsert';
export { apiincidentcommentinsert } from './fn/operations/apiincidentcommentinsert';
export type { Apiincidentcommentgetall$Params } from './fn/operations/apiincidentcommentgetall';
export { apiincidentcommentgetall } from './fn/operations/apiincidentcommentgetall';

export type { Apicategorygetall$Params } from './fn/operations/apicategorygetall';
export { apicategorygetall } from './fn/operations/apicategorygetall';

export type { Apiservicestatusgetall$Params } from './fn/operations/apiservicestatusgetall';
export { apiservicestatusgetall } from './fn/operations/apiservicestatusgetall';
export type { Apiservicestatusupdate$Params } from './fn/operations/apiservicestatusupdate';
export { apiservicestatusupdate } from './fn/operations/apiservicestatusupdate';

export type { Apiannouncementgetactive$Params } from './fn/operations/apiannouncementgetactive';
export { apiannouncementgetactive } from './fn/operations/apiannouncementgetactive';
export type { Apiannouncementgetallforadmin$Params } from './fn/operations/apiannouncementgetallforadmin';
export { apiannouncementgetallforadmin } from './fn/operations/apiannouncementgetallforadmin';
export type { Apiannouncementinsert$Params } from './fn/operations/apiannouncementinsert';
export { apiannouncementinsert } from './fn/operations/apiannouncementinsert';
export type { Apiannouncementdeactivate$Params } from './fn/operations/apiannouncementdeactivate';
export { apiannouncementdeactivate } from './fn/operations/apiannouncementdeactivate';

export type { Apiknowledgearticlegetall$Params } from './fn/operations/apiknowledgearticlegetall';
export { apiknowledgearticlegetall } from './fn/operations/apiknowledgearticlegetall';
export type { Apiknowledgearticleregisterview$Params } from './fn/operations/apiknowledgearticleregisterview';
export { apiknowledgearticleregisterview } from './fn/operations/apiknowledgearticleregisterview';
export type { Apiknowledgearticleinsert$Params } from './fn/operations/apiknowledgearticleinsert';
export { apiknowledgearticleinsert } from './fn/operations/apiknowledgearticleinsert';
export type { Apiknowledgearticledeactivate$Params } from './fn/operations/apiknowledgearticledeactivate';
export { apiknowledgearticledeactivate } from './fn/operations/apiknowledgearticledeactivate';
export type { Apiprioritygetall$Params } from './fn/operations/apiprioritygetall';
export { apiprioritygetall } from './fn/operations/apiprioritygetall';
export type { Apitechniciangetall$Params } from './fn/operations/apitechniciangetall';
export { apitechniciangetall } from './fn/operations/apitechniciangetall';

export type { Apicontactgetall$Params } from './fn/operations/apicontactgetall';
export { apicontactgetall } from './fn/operations/apicontactgetall';

export type { Apicontactsendmessage$Params } from './fn/operations/apicontactsendmessage';
export { apicontactsendmessage } from './fn/operations/apicontactsendmessage';

export type { Apinotificationgetall$Params } from './fn/operations/apinotificationgetall';
export { apinotificationgetall } from './fn/operations/apinotificationgetall';
export type { Apinotificationmarkread$Params } from './fn/operations/apinotificationmarkread';
export { apinotificationmarkread } from './fn/operations/apinotificationmarkread';
export type { Apinotificationmarkallread$Params } from './fn/operations/apinotificationmarkallread';
export { apinotificationmarkallread } from './fn/operations/apinotificationmarkallread';

export type { Apireportsummary$Params } from './fn/operations/apireportsummary';
export { apireportsummary } from './fn/operations/apireportsummary';
